#include <unity.h>
#include <limits>
#include <initializer_list>
#include "SmartPlugReliability.h"
#include "SmartPlugMetering.h"
#include "SmartPlugCredentialVault.h"
using namespace smartplug_reliability;
using smartplug_credentials::Credential;
using smartplug_credentials::Role;
using smartplug_credentials::kMaxCredentials;
using smartplug_credentials::kRecordBytes;
void setUp() {}
void tearDown() {}
void roundTrip() { auto r = energyRecord(42, 12345678.125); uint32_t s; double v; TEST_ASSERT_TRUE(decode(r,s,v)); TEST_ASSERT_EQUAL_UINT32(42,s); TEST_ASSERT_TRUE(v == 12345678.125); }
void rejectsEachCorruptedByte() { auto r = energyRecord(42,125); for (size_t i=0;i<sizeof(r);++i) {auto broken=r;broken.bytes[i]^=1;uint32_t s;double v;TEST_ASSERT_FALSE(decode(broken,s,v));} }
void rejectsInvalidValues() {for(double v:{-1.0,1.1e12,std::numeric_limits<double>::infinity(),std::numeric_limits<double>::quiet_NaN()}){auto r=energyRecord(1,v);uint32_t s;double x;TEST_ASSERT_FALSE(decode(r,s,x));} }
void acceptsBoundaries() {for(double v:{0.0,1.0e12}){auto r=energyRecord(1,v);uint32_t s;double x;TEST_ASSERT_TRUE(decode(r,s,x));} }
void selectsSurvivingSlot() { TEST_ASSERT_EQUAL_INT(-1,newestSlot(false,1,false,2));TEST_ASSERT_EQUAL_INT(0,newestSlot(true,1,false,2));TEST_ASSERT_EQUAL_INT(1,newestSlot(false,1,true,2));TEST_ASSERT_EQUAL_INT(1,newestSlot(true,1,true,2)); }
void sequenceWrap() {TEST_ASSERT_EQUAL_INT(1,newestSlot(true,0xffffffffU,true,0));TEST_ASSERT_EQUAL_INT(0,newestSlot(true,0,true,0xffffffffU));}
void truncatedWriteKeepsPrevious() {
  const auto old=energyRecord(20,400), next=energyRecord(21,500);
  for(size_t count=0;count<sizeof(next);++count){ EnergyRecord partial;std::memset(&partial,0xff,sizeof(partial));std::memcpy(&partial,&next,count);uint32_t sa=0,sb=0;double a=0,b=0;bool av=decode(old,sa,a),bv=decode(partial,sb,b);TEST_ASSERT_EQUAL_INT(0,newestSlot(av,sa,bv,sb));TEST_ASSERT_TRUE(a==400); }
}
void freshnessWrapAndUnavailable() {TEST_ASSERT_FALSE(fresh(false,0,0));TEST_ASSERT_TRUE(fresh(true,6000,1000));TEST_ASSERT_FALSE(fresh(true,6001,1000));TEST_ASSERT_TRUE(fresh(true,100,0xfffffff0U));}
void bootNeedsConsecutiveSamples() {BootRelayDecision d;TEST_ASSERT_EQUAL_INT(-1,d.observe(false));TEST_ASSERT_EQUAL_INT(-1,d.observe(true));TEST_ASSERT_EQUAL_INT(-1,d.observe(false));TEST_ASSERT_EQUAL_INT(-1,d.observe(false));TEST_ASSERT_EQUAL_INT(0,d.observe(false));}
void invalidResetsBootCandidate() {BootRelayDecision d;d.observe(true);d.observe(true);d.invalid();TEST_ASSERT_EQUAL_INT(-1,d.observe(true));TEST_ASSERT_EQUAL_INT(-1,d.observe(true));TEST_ASSERT_EQUAL_INT(1,d.observe(true));}
void strictCalibrationNumbers() {double v;TEST_ASSERT_TRUE(positiveNumber("12.5",v));for(const char* s:{"","abc","12junk","nan","inf","0","-1","1e500"})TEST_ASSERT_FALSE(positiveNumber(s,v));}
void syncNeverDecreases() {smartplug_metering::EnergyIntegrator e;e.restoreEnergyWh(100);TEST_ASSERT_FALSE(e.syncEnergyWh(99));TEST_ASSERT_FALSE(e.syncEnergyWh(100));TEST_ASSERT_FALSE(e.syncEnergyWh(NAN));TEST_ASSERT_TRUE(e.syncEnergyWh(101));TEST_ASSERT_TRUE(e.energyWh()==101);}
void syncPreservesCfBaseline() {smartplug_metering::EnergyIntegrator e;smartplug_metering::Calibration c={.01F,.01F,.01F,.01F};bl0940_protocol::RawMeasurement r={};r.cfCount=10;e.update(r,c,1000);e.syncEnergyWh(100);r.cfCount=11;auto sample=e.update(r,c,1500);TEST_ASSERT_TRUE(sample.energyWhSinceBoot>100.009&&sample.energyWhSinceBoot<100.011);}
Credential credential(const char* id, Role role) { Credential value={}; std::strncpy(value.id,id,sizeof(value.id)-1); value.role=role; std::memcpy(value.salt,"0123456789abcdef",16); std::memcpy(value.verifier,"0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",64); return value; }
void credentialVaultRoundTrip() { Credential input[2]={credential("owner-000001",Role::owner),credential("member-00001",Role::member)},output[kMaxCredentials]={}; auto record=smartplug_credentials::makeRecord(42,input,2);uint32_t sequence=0;uint8_t count=0;TEST_ASSERT_TRUE(smartplug_credentials::decode(record,sequence,output,count));TEST_ASSERT_EQUAL_UINT32(42,sequence);TEST_ASSERT_EQUAL_UINT8(2,count);TEST_ASSERT_EQUAL_STRING("owner-000001",output[0].id);TEST_ASSERT_EQUAL_STRING("member-00001",output[1].id);TEST_ASSERT_EQUAL_INT(1,smartplug_credentials::findCredential(output,count,"member-00001")); }
void credentialVaultRejectsCorruptionAndInvalidOwnership() { Credential input[2]={credential("owner-000001",Role::owner),credential("member-00001",Role::member)},output[kMaxCredentials]={}; auto record=smartplug_credentials::makeRecord(42,input,2); for(size_t i=0;i<kRecordBytes;++i){auto broken=record;broken.bytes[i]^=1;uint32_t sequence=0;uint8_t count=0;TEST_ASSERT_FALSE(smartplug_credentials::decode(broken,sequence,output,count));} input[1].role=Role::owner;record=smartplug_credentials::makeRecord(1,input,2);uint32_t sequence=0;uint8_t count=0;TEST_ASSERT_FALSE(smartplug_credentials::decode(record,sequence,output,count)); }
void credentialVaultKeepsPreviousSlotOnPartialNextWrite() { Credential oldInput[1]={credential("owner-000001",Role::owner)},newInput[2]={credential("owner-000001",Role::owner),credential("member-00001",Role::member)},output[kMaxCredentials]={};auto oldRecord=smartplug_credentials::makeRecord(7,oldInput,1),nextRecord=smartplug_credentials::makeRecord(8,newInput,2);for(size_t bytes=0;bytes<kRecordBytes;++bytes){smartplug_credentials::Record partial={};std::memcpy(partial.bytes,nextRecord.bytes,bytes);uint32_t oldSequence=0,newSequence=0;uint8_t oldCount=0,newCount=0;bool oldValid=smartplug_credentials::decode(oldRecord,oldSequence,output,oldCount),newValid=smartplug_credentials::decode(partial,newSequence,output,newCount);TEST_ASSERT_EQUAL_INT(0,smartplug_credentials::newestSlot(oldValid,oldSequence,newValid,newSequence));}}
void credentialVaultRecoversAcrossSequenceWrap() { Credential owner[1]={credential("owner-000001",Role::owner)}, output[kMaxCredentials]={};auto beforeWrap=smartplug_credentials::makeRecord(0xffffffffU,owner,1), afterWrap=smartplug_credentials::makeRecord(0U,owner,1);uint32_t a=0,b=0;uint8_t ca=0,cb=0;TEST_ASSERT_TRUE(smartplug_credentials::decode(beforeWrap,a,output,ca));TEST_ASSERT_TRUE(smartplug_credentials::decode(afterWrap,b,output,cb));TEST_ASSERT_EQUAL_INT(1,smartplug_credentials::newestSlot(true,a,true,b));}
void credentialVaultUsesSurvivingSlotAndFailsClosedWhenBothInvalid() { Credential owner[1]={credential("owner-000001",Role::owner)}, output[kMaxCredentials]={};auto previous=smartplug_credentials::makeRecord(10U,owner,1), newer=smartplug_credentials::makeRecord(11U,owner,1);newer.bytes[0]^=0x80U;uint32_t previousSequence=0,newerSequence=0;uint8_t previousCount=0,newerCount=0;const bool previousValid=smartplug_credentials::decode(previous,previousSequence,output,previousCount);const bool newerValid=smartplug_credentials::decode(newer,newerSequence,output,newerCount);TEST_ASSERT_TRUE(previousValid);TEST_ASSERT_FALSE(newerValid);TEST_ASSERT_EQUAL_INT(0,smartplug_credentials::newestSlot(previousValid,previousSequence,newerValid,newerSequence));previous.bytes[kRecordBytes - 1U]^=0x01U;uint32_t ignoredSequence=0;uint8_t ignoredCount=0;TEST_ASSERT_FALSE(smartplug_credentials::decode(previous,ignoredSequence,output,ignoredCount));TEST_ASSERT_EQUAL_INT(-1,smartplug_credentials::newestSlot(false,0U,false,0U));}
// ESP8266's Arduino core declares these entry points with C linkage.  This
// test file intentionally does not include Arduino.h, so keep the linkage
// explicit rather than relying on the production source or an upload target.
extern "C" void setup(){UNITY_BEGIN();RUN_TEST(roundTrip);RUN_TEST(rejectsEachCorruptedByte);RUN_TEST(rejectsInvalidValues);RUN_TEST(acceptsBoundaries);RUN_TEST(selectsSurvivingSlot);RUN_TEST(sequenceWrap);RUN_TEST(truncatedWriteKeepsPrevious);RUN_TEST(freshnessWrapAndUnavailable);RUN_TEST(bootNeedsConsecutiveSamples);RUN_TEST(invalidResetsBootCandidate);RUN_TEST(strictCalibrationNumbers);RUN_TEST(syncNeverDecreases);RUN_TEST(syncPreservesCfBaseline);RUN_TEST(credentialVaultRoundTrip);RUN_TEST(credentialVaultRejectsCorruptionAndInvalidOwnership);RUN_TEST(credentialVaultKeepsPreviousSlotOnPartialNextWrite);RUN_TEST(credentialVaultRecoversAcrossSequenceWrap);RUN_TEST(credentialVaultUsesSurvivingSlotAndFailsClosedWhenBothInvalid);UNITY_END();}
extern "C" void loop() {}
